# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 333713399ffe536d63630aa61c417927d02b5ec152936fe9c3786a5e347ff78ed1890d79f2259471e362588eeebed8fa14665e301461d9eadcfc0253a45adf2a

test:
  secret_key_base: e185e868710fa28688fda63290bed8e2200a6e59aaeb4586e84318b35731c7c28adc658b82a68baa034386ee1c51d8ef5007e02d45ef7e27d52571e7e2258463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 06bf32dc62ed65bcff4d35508e03c8a07eb3b38f9916c1b34bb0307e010accb91b380239acc51756dda2be6797d756e4aa8737fc06517436d578ccd5817f50d5
